// dummy accounts on stellar testnet network
const a = {
  public: 'GCSUOI5UM66YUL4HBVP4GXS4TRREY7Z3DKMYPAOYIEI3XRTHIABB7B4F',
  secret: 'SBTR7OUPLJ7YXMG4F6UEJAHHBGD7O7TJOXCO4WJ4TWNFHDEGRUEBVYQ6',
  email: 'kunderwood510@gmail.com'
}

const b = {
  public: 'GBIZUAYHION4PRYXDWOQFSAXJBJ5G5MUVBBYIQRBCA4V6B6EJ42LU3WN',
  secret: 'SCHKHPDOPURDODUNWRGUUYYOQ7XI662LZPLJKH7PG4RXEC4LPJM2G5PE',
  email: 'kunderwood510@gmail.com'
}

module.exports = {a, b}
